---
title: Your awesome title
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: carlos@gobo.tv
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: "/Curso2016"
url: http://yourdomain.com
twitter_username: gobotw
github_username: gobogit
markdown: kramdown
kramdown:
  parse_block_html: true
  input: GFM
  hard_wrap: false
  highlighter: rouge
include:
- _pages
permalink: "/:title/"
sass_dir: _sass
sass:
  style: :compressed
